# -*- coding: utf-8 -*-
"""Regresion lineal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlBCi4NYvqRHjpWG0xMsTWTQYdRjXKR5
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import RobustScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split,cross_validate,cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

#carga de dataset
df = sns.load_dataset('penguins')

df.head()

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

"""vamos a imputar los valores faltanste

body_mass_g
"""

medias_body = df.groupby('species')['body_mass_g'].mean()
print(medias_body)

columna_espejo_body =df.groupby('species')['body_mass_g'].transform('median')

print(columna_espejo_body)

df['body_mass_g'] = df['body_mass_g'].fillna(columna_espejo_body)

"""bill_length_mm"""

medias_por_especie=df.groupby('species')['bill_length_mm'].mean()
print(medias_por_especie)

# Creamos una serie que repite la mediana correspondiente para cada fila
columna_espejo_medianas = df.groupby('species')['bill_length_mm'].transform('median')

# Vamos a ver las primeras 5 filas de esa plantilla para entenderla
print(columna_espejo_medianas.head())

# Reemplazamos la columna original con la versión rellenada
df['bill_length_mm'] = df['bill_length_mm'].fillna(columna_espejo_medianas)

"""bill_depth_mm


"""

medias_por_especie_bill_depth = df.groupby('species')['bill_depth_mm'].mean()
print(medias_por_especie_bill_depth)

# Creamos una serie que repite la mediana correspondiente para cada fila
columna_espejo_medianas_bill_depth_mm = df.groupby('species')['bill_depth_mm'].transform('median')

# Vamos a ver las primeras 5 filas de esa plantilla para entenderla
print(columna_espejo_medianas_bill_depth_mm.head())

df['bill_depth_mm']  = df["bill_depth_mm"].fillna(columna_espejo_medianas_bill_depth_mm)

"""flipper_length_mm

"""

medias_por_especie_filper_length_mm = df.groupby('species')['flipper_length_mm'].mean()
print(medias_por_especie_filper_length_mm)

col_espejo_fil = df.groupby('species')['flipper_length_mm'].transform('median')
print(col_espejo_fil.head())

df['flipper_length_mm'] = df['flipper_length_mm'].fillna(col_espejo_fil)

"""One hot coding"""

encoder = OneHotEncoder(drop='first',sparse_output=False)
especies_transfromadas = encoder.fit_transform(df[['species']])

print(especies_transfromadas)

"""
import pandas as pd

# 1. Convertimos la matriz suelta en un DataFrame de Pandas con nombres de columnas correctos
columnas_nuevas = encoder.get_feature_names_out(['species'])
df_especies = pd.DataFrame(especies_transformadas, columns=columnas_nuevas, index=df_modelo.index)

# 2. Unimos (concatenamos) las nuevas columnas a tu dataset original
df_modelo = pd.concat([df_modelo, df_especies], axis=1)

# 3. Borramos la columna 'species' vieja que todavía estaba en texto
df_modelo = df_modelo.drop(columns=['species'])

# ¡Listo! Ahora sí revisamos la tabla final
print(df_modelo.head())
"""

print("graficas categoricas")
colm_cat = df.select_dtypes(include=["object"]).columns

for col in colm_cat:
  plt.figure(figsize=(6, 4))
  counts =df[col].value_counts()
  counts.plot(kind="bar", color="lightgreen", edgecolor="black")

  plt.title(f"Distribucion de {col}",fontsize=12)
  plt.xlabel(col)
  plt.ylabel("Frecuencia")
  plt.grid(axis="y", linestyle="--", alpha=0.7)
  plt.tight_layout()
  plt.show()

print("graficas categoricas")
colm_num = df.select_dtypes(include=["number"]).columns

for col in colm_num:
  plt.figure(figsize=(6, 4))
  counts =df[col].value_counts()
  df[col].plot(kind="hist", bins=20, color="skyblue", edgecolor="black", alpha=0.7)

  plt.title(f"Distribucion de {col}",fontsize=12)
  plt.xlabel(col)
  plt.ylabel("Frecuencia")
  plt.grid(axis="y", linestyle="--", alpha=0.7)
  plt.tight_layout()
  plt.show()

print("Generando Boxplots...")
# Seleccionamos solo las columnas numéricas
colm_num = df.select_dtypes(include=["number"]).columns

for col in colm_num:
    plt.figure(figsize=(4,5))

    # Usamos Seaborn para que maneje los nulos automáticamente,
    # pero le pasamos los estilos que a ti te gustan
    sns.boxplot(y=df[col],  # Aquí le pasamos los DATOS reales de la columna
                patch_artist=True,
                boxprops=dict(facecolor='#a8dadc', color='blue'), # Caja azul con borde negro
                medianprops=dict(color='red', linewidth=1.5),      # Mediana roja
                flierprops=dict(marker='o', markerfacecolor='none', markeredgecolor='black'), # Outliers vacíos
                width=0.3) # Caja estilizada

    plt.title(f"Boxplot de {col}", fontsize=13)
    plt.ylabel(col)  # Como el gráfico es vertical (y=df[col]), el nombre va en el eje Y
    plt.grid(axis="y", linestyle="--", alpha=0.6) # Cuadrícula horizontal que cruza la caja

    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6, 4))
sns.scatterplot(data=df, x='flipper_length_mm', y='body_mass_g', hue='species', palette='dark')

plt.title("¿Hay relación lineal entre la aleta y el peso?", fontsize=12, fontweight='bold')
plt.xlabel("Largo de la Aleta (mm)")
plt.ylabel("Peso del Pingüino (g)")
plt.grid(True, linestyle="--", alpha=0.5)
plt.show()

sns.pairplot(df, hue='species')
plt.show()

"""correlacion de los datos"""

matriz_correlacion = df.corr(numeric_only=True)
print(matriz_correlacion['body_mass_g'])

"""creacion del nuevo dataset con los datos a usar en el modelo"""

df_modelo = df[['bill_length_mm', 'flipper_length_mm', 'body_mass_g']].copy()

columnas_nuevas = encoder.get_feature_names_out(['species'])
df_especies = pd.DataFrame(especies_transfromadas, columns=columnas_nuevas, index=df_modelo.index)

df_modelo = pd.concat([df_modelo, df_especies], axis=1)

df_modelo[columnas_nuevas] = df_modelo[columnas_nuevas].astype(int)

print(df_modelo.head())

"""modelo

separamos la variable clase con las otras
"""

X = df_modelo.drop(columns=['body_mass_g'])
y = df_modelo['body_mass_g']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

pipeline_regresion = Pipeline([
    ('scaler', RobustScaler()),# Escala datos ignorando valores atípicos
    ('modelo', LinearRegression())# El algoritmo matemático central
])

"""validacion crusza

"""

metricas_cv = ['r2', 'neg_mean_absolute_error', 'neg_root_mean_squared_error']
resultados_cv = cross_validate(pipeline_regresion, X_train, y_train, cv=5, scoring=metricas_cv)

print("=== RESULTADOS DE LA VALIDACIÓN CRUZADA (5 Folds) ===")
print(f"R² (Explicación de varianza) Promedio: {resultados_cv['test_r2'].mean():.2%}")
print(f"MAE (Error absoluto) Promedio: {-resultados_cv['test_neg_mean_absolute_error'].mean():.2f} gramos")
print(f"RMSE (Error penalizado) Promedio: {-resultados_cv['test_neg_root_mean_squared_error'].mean():.2f} gramos\n")

"""Entrenamiento del modleo y evaluacion"""

pipeline_regresion.fit(X_train, y_train)

predicciones = pipeline_regresion.predict(X_test)

r2_final = r2_score(y_test, predicciones)
mae_final = mean_absolute_error(y_test, predicciones)
rmse_final = np.sqrt(mean_squared_error(y_test, predicciones))

print("=== EVALUACIÓN FINAL EN EL EXAMEN REAL (Test Dataset) ===")
print(f"R² Final: {r2_final:.2%}")
print(f"MAE Final: {mae_final:.2f} gramos")
print(f"RMSE Final: {rmse_final:.2f} gramos\n")

modelo_final = pipeline_regresion.named_steps['modelo']
print("=== ECUACIÓN MATEMÁTICA DEL MODELO ===")
print(f"Intersección (Peso base cuando todo es 0): {modelo_final.intercept_:.2f} gramos\n")
importancia = pd.DataFrame({
    'Variable': X.columns,
    'Coeficiente (Impacto)': modelo_final.coef_
}).sort_values(by='Coeficiente (Impacto)', ascending=False)
print(importancia.to_string(index=False))

