# -*- coding: utf-8 -*-
"""Regresion lineal limpia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1osf9McHK6d8J1bjM0n6O6gmOfeoo5M
"""

import pandas as pd # es para manerjar tablas o crear df
import seaborn as sns #para visualizar más estadisticas o subir dataser que ya vienen
import numpy as np # para las operaciones matematicas peromite manejar vectores matrices y operaciones numericas
import matplotlib.pyplot as plt #sirve para personalizar los graficos ponre titulos ejes
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler #convierte texto variables categoricas a numeros binarios
from sklearn.preprocessing import RobustScaler# escala y normaliza losnumeros para que esten en un ragno similar
from sklearn.pipeline import Pipeline#te permite empaquetar en un solo obejto el orden de los pasos
from sklearn.model_selection import train_test_split,cross_validate,cross_val_score

#train_test_split divide tus datos en dos grupos uno para entrenamiento y uno para el modelo 80% y 20%
#cross_validate y crol_val_score es para la validacion cruzada divide los datos en varias partes
#cross_val_score te devuelve solo las calificaciones directamente, mientras que cross_validate te da un reporte más detallado que incluye los tiempos de ejecución
#metricas de evalucacion
#r2_score coeficiente de determinacion te dice el porcentaje de variacion que tu modelo logra explicar si da .85 significa que tu  modelo explica el 85% del comportamiento mientras mas cercano a 1 mejor
#mean_squared_error MDE Error cuadratico medio mide que tan lejos estan las predicciones de la realidad elevando los erroes al cuadrado castigando con mucha fuerza los errores grandes se busca lo más cercano al 0
#mean_absolute_error MAE error absoluto medio te dice que promedio por cuantas unidades se equivoca elmodelo si el mea da 200 significa que el modelo erra el peso del pinguino por 200 gramos
from sklearn.linear_model import LinearRegression#Es el algoritmo que traza la línea (o plano) matemática para encontrar la relación entre las características del pingüino y su peso.
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

#Carga dataset
df = sns.load_dataset('penguins')

df.head()

df.columns

df.info()

df.describe()

df.isnull().sum()

"""imputacion de valores

body_mass_g

se saca la media por especie de body_mass_g
"""

colummna_espejo_body = df.groupby('species')['body_mass_g'].transform('mean')

df['body_mass_g'] = df['body_mass_g'].fillna(colummna_espejo_body)

"""se saca la media por especie de flipper_length_mm"""

colummna_espejo_flipper = df.groupby('species')['flipper_length_mm'].transform('mean')

df['flipper_length_mm'] = df['flipper_length_mm'].fillna(colummna_espejo_flipper)

"""se saca la media por especie de bill_depth_mm"""

columa_espejo_bill = df.groupby('species')['bill_depth_mm'].transform('mean')

df['bill_depth_mm'] = df['bill_length_mm'].fillna(columa_espejo_bill)

"""se saca la media por especie de bill_length_mm"""

columna_espejo_bill_length = df.groupby('species')['bill_length_mm'].transform('mean')

df['bill_length_mm'] = df['bill_length_mm'].fillna(columna_espejo_bill_length)

"""imputar valores por especie"""

df['sex'] = df.groupby('species')['sex'].transform(lambda x: x.fillna(x.mode()[0]))

df.isnull().sum()

"""one hot coding

"""

encoder = OneHotEncoder(drop='first',sparse_output=False)
especies_transformadas = encoder.fit_transform(df[['species']])

print(especies_transformadas)

df['bill_length_mm'] = df['bill_length_mm'].astype(float)
df['bill_depth_mm'] = df['bill_depth_mm'].astype(float)

"""se muestran las graficas para ver las correlaciones"""

sns.pairplot(df, hue='species')
plt.show()

matriz_correlacion = df.corr(numeric_only=True)
print(matriz_correlacion['body_mass_g'])

df_modelo = df[['bill_length_mm', 'flipper_length_mm', 'body_mass_g']].copy()

columnas_nuevas = encoder.get_feature_names_out(['species'])
df_especies = pd.DataFrame(especies_transformadas, columns=columnas_nuevas, index=df_modelo.index)

df_modelo = pd.concat([df_modelo, df_especies], axis=1)

df_modelo[columnas_nuevas] = df_modelo[columnas_nuevas].astype(int)

print(df_modelo.head())

df_modelo.info()

"""separar datos"""

X = df_modelo.drop(columns=['body_mass_g'])
y = df_modelo['body_mass_g']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=42)

pipeline_regresion = Pipeline([
    ('scaler', RobustScaler()),# Escala datos ignorando valores atípicos
    ('modelo', LinearRegression())# El algoritmo matemático central
])

metricas_cv = ['r2', 'neg_mean_absolute_error', 'neg_root_mean_squared_error']
resultados_cv = cross_validate(modelo,
                               X_train,
                               y_train,
                               cv=5,
                               scoring=metricas_cv)

print("=== RESULTADOS DE LA VALIDACIÓN CRUZADA (5 Folds) ===")
print(f"R² (Explicación de varianza) Promedio: {resultados_cv['test_r2'].mean():.2%}")
print(f"MAE (Error absoluto) Promedio: {-resultados_cv['test_neg_mean_absolute_error'].mean():.2f} gramos")
print(f"RMSE (Error penalizado) Promedio: {-resultados_cv['test_neg_root_mean_squared_error'].mean():.2f} gramos\n")

pipeline_regresion.fit(X_train, y_train)

predicciones = pipeline_regresion.predict(X_test)

r2_final = r2_score(y_test, predicciones)
mae_final = mean_absolute_error(y_test, predicciones)
rmse_final = np.sqrt(mean_squared_error(y_test, predicciones))

print("=== EVALUACIÓN FINAL EN EL EXAMEN REAL (Test Dataset) ===")
print(f"R² Final: {r2_final:.2%}")
print(f"MAE Final: {mae_final:.2f} gramos")
print(f"RMSE Final: {rmse_final:.2f} gramos\n")

print("=== ECUACIÓN MATEMÁTICA DEL MODELO ===")

print(f"Intersección: {modelo.intercept_:.2f}\n")

importancia = pd.DataFrame({
    'Variable': X.columns,
    'Coeficiente (Impacto)': modelo.coef_
}).sort_values(by='Coeficiente (Impacto)', ascending=False)

print(importancia.to_string(index=False))

import matplotlib.pyplot as plt

plt.scatter(y_test, predicciones)

plt.xlabel("Valores reales")
plt.ylabel("Predicciones")
plt.title("Real vs Predicción")

plt.show()

import numpy as np

plt.scatter(y_test, predicciones)

line = np.linspace(min(y_test), max(y_test), 100)
plt.plot(line, line, color="red")

plt.xlabel("Real")
plt.ylabel("Predicho")
plt.show()

print(X.columns)

import pandas as pd

nuevo = pd.DataFrame([[
    40,   # bill_length_mm
    200,  # flipper_length_mm
    0,    # species_Chinstrap
    1     # species_Gentoo
]], columns=X.columns)

print(pipeline_regresion.predict(nuevo))

